### ISSUE TITLE
调用通知模块实现通知记录功能

### ISSUE THREAD

**Issue by ben7th** [kc-train/question_mod#4]
1. 在 sample 中引用李博超开发的通知模块：  
   https://github.com/kc-train/kc_notifications  
   以引入通知模型
   （关于通知模块的模型使用方法和记录添加方法，和李博超沟通）
2. 在用户使用问答模块功能的过程中，在指定的时机添加通知记录：
   - 用户的问题被其他用户回答时
   - 用户的回答被其他用户投赞成/反对票时
3. 编写必要的测试代码

---

把大致的实现思路和步骤回复在该 issue 里，便于跟踪

**Comment by hengtangan2025** [comment]
实现思路
      1.每当一个回答被创建之后，为该回答所关联的问题的创建者发送一个问答通知，即为该回答所关联的问题的创建者创建一个回答通知，内容为“你的问题 XXX 收到了1个新的回答”。计划在answer.rb中使用回调方法实现。

```
  2.每当一个vote被创建之后，为该vote所关联的问题或回答的创建者发送一个问答通知，内容为“你的问题 XXX / 在问题 XXX 下的回答  获得了一次 赞/踩”。计划在vote.rb中使用回调方法实现。
```

执行步骤
      1.引入通知模块
      2.编写测试代码
      3.添加通知记录
